# Generated by Django 2.1.7 on 2019-02-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trains', '0002_auto_20190227_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва маршруту')),
                ('from_city', models.CharField(max_length=100, verbose_name='Звідки')),
                ('to_city', models.CharField(max_length=100, verbose_name='Куди')),
                ('across_cities', models.ManyToManyField(blank=True, to='trains.Train', verbose_name='Час у дорозі')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршрути',
                'ordering': ['name'],
            },
        ),
    ]
