# Generated by Django 2.1.1 on 2019-03-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='travel_times',
            field=models.IntegerField(default=10, verbose_name='Время в пути'),
            preserve_default=False,
        ),
    ]
